### ISSUE TITLE
Crashes on import() dynamic import

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [jimmywarting/not-a-log#2]
When trying to load the `not-a-log` module with a [dynamic `import()` expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import)...

```js
await import("not-a-log").then(mod => mod.default);
```

...the Proxy attempt to wrap around the `'then'` prop and that throws an error:

```plaintext
$ node index.js
file:///Users/josh/repos/repros/node_modules/not-a-log/not-a-log.js:9
    return new Proxy(logger[prop], handler)
           ^

TypeError: Cannot create proxy with a non-object as target or handler
    at Object.get (file:///Users/josh/repos/repros/node_modules/not-a-log/not-a-log.js:9:12)
    at async file:///Users/josh/repos/repros/index.js:1:1

Node.js v22.4.1
```

I first experienced this trying to run code that imports `not-a-log` with Vitest: https://github.com/vitest-dev/vitest/issues/6115. @hi-ogawa noted this simpler reproduction in https://github.com/vitest-dev/vitest/issues/6115#issuecomment-2244128356 (thanks again!).

**Comment by hi-ogawa** [comment]
Just to clarify, there is definitely a bug in Vitest and ideally Vitest should support `not-a-log` as is.

What I meant is that `not-a-log` can be potentially made more robust around `then` (or any other unexpected property access) since that can happen with simple `await` expression (thought it's understandably odd use usage).

**Comment by JoshuaKGoldberg** [comment]
👋 Ping @jimmywarting, just checking in - would you be open to a PR to make `not-a-log` more robust around `then` or other unexpected property accesses?

**Comment by jimmywarting** [comment]
Uhm, sure. I would rather that vitest supported this as is... Anyway... before you create a PR, how would you propose to solve this? Validating property access sounds better than doing special treatment for "then"

**Comment by JoshuaKGoldberg** [comment]
Great! Yeah, I was planning on trying to solve this generally. Nothing specific to Vitest. Maybe, having `handler.get` only return a `new Proxy` if `logger[prop]` is actually defined?

**Comment by jimmywarting** [comment]
> having `handler.get` only return a `new Proxy` if `logger[prop]` is actually defined?

if that works 👍
